name: Generate Anki Deck
on:
  push:
    branches: [ main ] # 當你向 main 分支提交代碼時觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install genanki

    - name: Run script
      run: python scripts/gen_anki.py

    - name: Upload Anki Deck
      uses: actions/upload-artifact@v3
      with:
        name: anki-package
        path: language_notes.apkg
